version: '3.10'
services:
  web:
    build: ./facepad
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./facepad:/usr/src/facepad
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=facepad_user
      - POSTGRES_PASSWORD=facepad_password
      - POSTGRES_DB=facepad_dev
volumes:
  postgres_data: