# Generated by Django 4.1.7 on 2023-02-16 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_friendrequest_requestee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
